<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Iniciar sesión</title>
</head>

<body>
  <form action="index.php?controller=usuarios&action=login" method="post">
    <div class="container">
      <label><b>Usuario</b></label>
      <input id="name" type="text" placeholder="Introduce usuario" name="username" required>
      <label><b>Contraseña</b></label>
      <input type="password" placeholder="Introduce contraseña" name="password" required>
      <input type="submit" name="login" value="Iniciar sesión">
    </div>
  </form>
</body>
</html>
